### ISSUE TITLE
JEDI1.13.5 Environment modules on Orion

### ISSUE THREAD

**Issue by mmiesch** [JCSDA-internal/jedi-stack-old#107]
Maintain environment modules on Orion

**Modules:** 

```
export JEDI_OPT=/work/noaa/da/grubin/opt/modules
module use $JEDI_OPT/modulefiles/core
```

Intel modules:
`module load jedi/intel-impi`

GNU modules:
`module load jedi/gnu-openmpi`

**Tasks:**

build for Intel 20 (20.0.166)

- [x]  build for Intel and Intel MPI (v20)
- [x]  update versions of modules as appropriate
- [x]  test against ufo and fv3 bundles

build for GNU (v8.3.0)
- [x]  build for GNU and OpenMPI (v4.0.2)
- [x]  update versions of modules as appropriate
- [x]  test against ufo and fv3 bundles

**Done:**

- [x] modules as per Tasks are built
- [x] test as per Tasks pass with new modules built

**C++ 14 support for JEDI**

**Tasks:**

- [x] C++ 14 support added per these flags in `buildscripts/config/config_orion.sh`:
  - [x] `CXXFLAGS="-std=c++14"`
  - [x] `LDFLAGS="-std=c++14"`
  - [x] load system-provided GNU C++ 14 to Intel-based JEDI meta-modules:
    - in `$JEDI_OPT/modulefiles/core/jedi-intel/2020.lua` (Intel 20.0.166 compiler suite), add
    - `load("jedi-gcc/8.3.0")`
    - `jedi-gcc/8.3.0` is a copy of the system-provided module file for the GNU C and C++ compilers

**Done:**

 - [x] ufo-bundle tests pass
 - [x] fv3 bundle tests pass
