### ISSUE TITLE
build for Intel 20 

### ISSUE THREAD

**Issue by rickgrubin** [JCSDA-internal/jedi-stack-old#131]
Maintain environment modules on Orion

**Modules**

**Tasks**:
- [x] build for Intel 20
    - [x] Intel MPI
    - [x] OpenMP
- [x] update versions of modules as appropriate
- [x] test against ufo and fv3 bundles

**Done**:
- [x] modules as per Tasks are built
- [x] test as per Tasks pass with new modules built
    - [x] ufo
    - [x] fv3

--

```
export OPT=/work/noaa/da/grubin/opt/modules
module use -a $OPT/modulefiles/core
module load jedi/intel-impi
```
or

`module load jedi/intel-openmpi`

Example test results:

**_ufo_**
100% tests passed, 0 tests failed out of 769

Subproject Time Summary:
eckit    =  27.30 sec*proc (115 tests)
fckit    =  24.60 sec*proc (14 tests)
gsw      =   1.15 sec*proc (2 tests)
ioda     = 141.04 sec*proc (21 tests)
oops     =  89.48 sec*proc (167 tests)
saber    = 327.66 sec*proc (149 tests)
ufo      = 879.87 sec*proc (167 tests)

Label Time Summary:
atlas            =  72.84 sec*proc (134 tests)
download_data    =  60.55 sec*proc (2 tests)
executable       = 397.43 sec*proc (362 tests)
fortran          =   9.16 sec*proc (36 tests)
mpi              = 303.24 sec*proc (118 tests)
openmp           = 271.46 sec*proc (123 tests)
script           = 1084.87 sec*proc (403 tests)

Total Test time (real) = 1567.27 sec

**_fv3_**
100% tests passed, 0 tests failed out of 104

Label Time Summary:
fv3-jedi    = 464.25 sec*proc (103 tests)
fv3jedi     = 467.36 sec*proc (104 tests)
mpi         = 462.87 sec*proc (73 tests)
script      = 467.36 sec*proc (104 tests)

**Comment by mmiesch** [comment]
Issue moved to [JCSDA-internal/jedi-stack #25](https://github.com/JCSDA-internal/jedi-stack/issues/25) via [**ZenHub**](https://www.zenhub.com/)
